"""Router — POST /analyze: primeste articol, returneaza TCS + explicatii."""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from backend.pipeline.graph.models import Article, Inconsistency
from backend.dependencies import get_orchestrator, explainer

logger = logging.getLogger(__name__)
router = APIRouter(tags=["analyze"])


# Pydantic schemas (request / response)
class AnalyzeRequest(BaseModel):
    """Input: article text + optional metadata."""
    text: str = Field(..., min_length=20, description="Article text")
    title: str = Field(default="", description="Article title")
    publication_date: Optional[str] = Field(default=None, description="Publication date (YYYY-MM-DD)")
    source: str = Field(default="", description="Article source")
    pipeline: str = Field(default="spacy", description="Pipeline: 'spacy' or 'llm'")
    model: Optional[str] = Field(default=None, description="Specific model: en_core_web_trf, llama3, mistral, etc. None = pipeline default")
    persist: bool = Field(default=False, description="Save facts to Neo4j for cross-article analysis")


class InconsistencyResponse(BaseModel):
    type: str
    severity: str
    severity_label: str
    description: str
    evidence: Optional[str]
    verified_by: str
    sentence_indices: list[int]


class FactAnnotationResponse(BaseModel):
    sentence_idx: int
    subject: str
    predicate: str
    object: str
    time: str
    status: str
    color: str
    confidence: float
    extractor: str
    inconsistencies: list[str]


class AnalyzeResponse(BaseModel):
    """Output: TCS score + structured explanations."""
    score: float
    label: str
    summary: str
    n_claims: int
    n_inconsistencies: int
    coherence_factor: float
    inconsistency_details: list[InconsistencyResponse]
    fact_annotations: list[FactAnnotationResponse]
    timeline: list[dict]
    pipeline: str
    model: str = Field(default="", description="Model used")
    processing_time_ms: float
    article_id: Optional[str] = Field(default=None, description="Neo4j article ID (set when persist=True)")
    cross_article_inconsistencies: list[InconsistencyResponse] = Field(default_factory=list)
    llm_explanation: Optional[str] = Field(default=None, description="XAI explanation generated by LLM")


_explainer = explainer


def _to_inconsistency_response(inc: Inconsistency) -> InconsistencyResponse:
    """Serialize an Inconsistency dataclass to the API response model."""
    return InconsistencyResponse(
        type=inc.inconsistency_type.value,
        severity=inc.severity.value,
        severity_label=inc.severity.value.title(),
        description=inc.description,
        evidence=inc.evidence,
        verified_by=inc.verified_by,
        sentence_indices=inc.sentence_indices,
    )


# Endpoint
@router.post("/analyze", response_model=AnalyzeResponse)
async def analyze_article(req: AnalyzeRequest) -> AnalyzeResponse:
    """Analyze an article and return the TCS score with explanations."""
    from backend.config import AVAILABLE_MODELS

    # Validate pipeline
    if req.pipeline not in ("spacy", "llm"):
        raise HTTPException(status_code=400, detail=f"Unknown pipeline: '{req.pipeline}'. Options: 'spacy', 'llm'.")

    # Validate model (if provided)
    if req.model:
        available = AVAILABLE_MODELS.get(req.pipeline, {}).get("models", [])
        if req.model not in available:
            raise HTTPException(status_code=400, detail=f"Model '{req.model}' not available for pipeline '{req.pipeline}'. Options: {available}")

    # Parse publication date
    pub_date = None
    if req.publication_date:
        try:
            pub_date = datetime.strptime(req.publication_date, "%Y-%m-%d")
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD.")

    article = Article(
        text=req.text, title=req.title,
        publication_date=pub_date, source=req.source,
    )

    logger.info(f"/analyze: '{article.title[:50]}' ({len(article.text)} chars, pipeline={req.pipeline}, model={req.model or 'default'})")

    # Acquire persistent store if persist=True
    persistent_store = None
    if req.persist:
        from backend.config import NEO4J_ENABLED
        if NEO4J_ENABLED:
            from backend.pipeline.graph.factory import create_persistent_store
            persistent_store = create_persistent_store()
        else:
            logger.warning("/analyze: persist=True but NEO4J_ENABLED=false")

    orchestrator = get_orchestrator(req.pipeline, req.model)
    orchestrator._persistent_store = persistent_store

    try:
        result = orchestrator.run(article)
    except Exception as e:
        logger.error(f"/analyze: pipeline error — {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal pipeline error.")
    finally:
        if persistent_store:
            persistent_store.close()

    article_id = result.article_id
    cross_article_inconsistencies = [
        _to_inconsistency_response(c) for c in result.cross_article_inconsistencies
    ]

    # Generate structured explanation
    explanation = _explainer.explain_structured(result)

    return AnalyzeResponse(
        score=result.score,
        label=result.label,
        summary=explanation["summary"],
        n_claims=result.n_temporal_claims,
        n_inconsistencies=result.n_inconsistencies,
        coherence_factor=result.coherence_factor,
        inconsistency_details=explanation["inconsistency_details"],
        fact_annotations=explanation["fact_annotations"],
        timeline=result.timeline,
        pipeline=result.pipeline_variant,
        model=req.model or AVAILABLE_MODELS[req.pipeline]["default"],
        processing_time_ms=result.processing_time_ms,
        article_id=article_id,
        cross_article_inconsistencies=cross_article_inconsistencies,
        llm_explanation=result.explanation_text if result.explanation_text and len(result.explanation_text) > 50 else None,
    )
