"""XAI — Natural language explanations generated by Qwen3-1.7B."""

from __future__ import annotations

import logging
from typing import Optional

from backend.pipeline.extraction.spacy_llm_extractor import _load_qwen, generate_json
from backend.pipeline.graph.models import TCSResult, TemporalFact

logger = logging.getLogger(__name__)

EXPLANATION_SYSTEM_PROMPT = """You are an expert fact-checker explaining the results of a temporal consistency analysis on a news article.

Given:
- A TCS (Temporal Coherence Score) between 0.0 and 1.0, where 1.0 = fully consistent and 0.0 = highly inconsistent
- A list of temporal facts extracted from the article
- A list of detected inconsistencies (if any)
- The article's metadata

Your task: write a clear, concise explanation (3-5 sentences) in English that:
1. States the overall assessment (consistent, suspicious, or unreliable)
2. Highlights the MOST IMPORTANT inconsistencies found (if any), with specific dates/entities
3. Mentions what was verified and how (internal logic, Wikidata, cross-article)
4. Gives actionable insight: should the reader trust this article's timeline?

Do NOT use bullet points. Write flowing prose. Be specific — mention actual entities and dates from the analysis.
If no inconsistencies were found, explain WHY the article appears consistent.

Respond with ONLY the explanation text. No preamble, no markdown."""


class LLMExplainer:
    """Generates XAI explanations using Qwen3-1.7B."""

    def is_available(self) -> bool:
        return _load_qwen()

    def explain(self, result: TCSResult, article_text: str = "", article_title: str = "") -> Optional[str]:
        """Generate an XAI explanation from a TCSResult."""
        context = self._build_context(result, article_text, article_title)
        messages = [
            {"role": "system", "content": EXPLANATION_SYSTEM_PROMPT},
            {"role": "user", "content": context},
        ]
        response = generate_json(messages)
        if not response:
            logger.warning("LLMExplainer: no response from Qwen")
            return None
        logger.info(f"LLMExplainer: explanation generated ({len(response)} chars)")
        logger.debug(f"LLMExplainer response: {response[:200]}...")
        return response

    def _build_context(self, result: TCSResult, article_text: str, article_title: str) -> str:
        parts = []

        parts.append(f"Article title: {article_title or 'Unknown'}")
        parts.append(f"TCS Score: {result.score:.3f} (label: {result.label})")
        parts.append(f"Temporal claims extracted: {result.n_temporal_claims}")
        parts.append(f"Inconsistencies detected: {result.n_inconsistencies}")
        parts.append(f"Pipeline: {result.pipeline_variant}")
        parts.append(f"Coherence factor: {result.coherence_factor:.3f}")

        if result.facts:
            parts.append("\nExtracted temporal facts:")
            for i, fact in enumerate(result.facts[:10]):
                time_str = _format_fact_time(fact)
                parts.append(f"  {i+1}. {fact.subject.text} — {fact.predicate.value} -> {fact.object.text} {time_str}")

        if result.inconsistencies:
            parts.append("\nDetected inconsistencies:")
            for i, inc in enumerate(result.inconsistencies):
                parts.append(f"  {i+1}. [{inc.severity.value}] {inc.inconsistency_type.value}: {inc.description}")
                if inc.evidence:
                    parts.append(f"     Evidence: {inc.evidence}")
        else:
            parts.append("\nNo inconsistencies detected.")

        if article_text:
            parts.append(f"\nArticle excerpt: {article_text[:500]}...")

        return "\n".join(parts)


def _format_fact_time(fact: TemporalFact) -> str:
    if fact.time_point and fact.time_point.date_string:
        return f"@{fact.time_point.date_string}"
    parts = []
    if fact.time_start and fact.time_start.date_string:
        parts.append(fact.time_start.date_string)
    if fact.time_end and fact.time_end.date_string:
        parts.append(fact.time_end.date_string)
    return f"[{' -> '.join(parts)}]" if parts else ""
